# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely edit after that. If you find
# yourself editing this file very often, consider using Jekyll's data files
# feature for the data you need to update frequently.
#
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'bundle exec jekyll serve'. If you change this file, please restart the server process.

# Site settings
# These are used to personalize your new site. If you look in the HTML files,
# you will see them accessed via {{ site.title }}, {{ site.email }}, and so on.
# You can create any custom variable you would like, and they will be accessible
# in the templates via {{ site.myvariable }}.
title: ИП "Мороз Н.К."
email: nm007@mail.ru
phone: +7 (911) 502-74-96
phone_plain: "89115027496"
post: 160001, г. Вологда, ул. Октябрьская, дом 13-а, офис 11
description: >-
  Официальный сайт ИП "Мороз Н.К." — производство и продажа устройств
  электроосмотической сушки и защиты от увлажнения изоляции электродвигателей,
  генераторов и трансформаторов. Вологда.
lang: ru
baseurl: ""
url: "https://moroznk.github.io"
twitter_username: 
github_username: 

# Build settings
markdown: kramdown
theme: minima
plugins:
  - jekyll-feed
  - jekyll-sitemap

permalink: /:categories/:title

collections:
  items:
    output: true

# Exclude from processing.
# The following items will not be processed, by default. Create a custom list
# to override the default setting.
exclude:
  - Gemfile
  - Gemfile.lock
